### PR TITLE
Polish Translation (Fixed format problem)

### PR DESCRIPTION
**Pull request by Thesussy**
Ok so the Translations should be now in right format, bcz this time i edited it in github itself. DSA Polish translation also included.

### CODE REVIEW

**Comment by 654Elemental** [comment]
@KamikaziF @erksmit how was your day?

**Comment by erksmit** [comment]
i am at a github pull request

**Comment by JustAnyones** [comment]
let me install windows 7 in peace

**Comment by Kulche458** [comment]
friendship with linux ended

**Comment by KamikaziF** [comment]
> @KamikaziF  how was your day?

Fine for the most part. Also, can you hit me in DMs pls

**Comment by Thesussy** [comment]
Noice conversation here.

**Pull request merged**
