### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by dream0004**

### CODE REVIEW

**Comment by lXero1** [comment]
All the lines have been removed in the .xml file...

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you down

**Comment by dream0004** [comment]
https://youtu.be/dQw4w9WgXcQ

**Comment by dream0004** [comment]
https://youtu.be/dQw4w9WgXcQ

**Comment by dream0004** [comment]
https://youtu.be/dQw4w9WgXcQ

**Comment by dream0004** [comment]
https://youtu.be/dQw4w9WgXcQ

**Comment by dream0004** [comment]
https://youtu.be/dQw4w9WgXcQ

**Comment by dream0004** [comment]
https://youtu.be/dQw4w9WgXcQ

**Comment by lXero1** [comment]
how old are you wtf

**Comment by dream0004** [comment]
https://youtu.be/dQw4w9WgXcQ

**Comment by dream0004** [comment]
@everyone

**Comment by dream0004** [comment]
@everyone

**Comment by dream0004** [comment]
https://youtu.be/dQw4w9WgXcQ

**Comment by dream0004** [comment]
https://youtu.be/dQw4w9WgXcQ

**Comment by dream0004** [comment]
Never gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you downNever gonna give you up, never gonna let you down

**Comment by JustAnyones** [comment]
Spam pull request.

**Pull request closed without merging**
